### ISSUE TITLE
Missing object hsmm_c1tpms.rds

### ISSUE THREAD

**Issue by ebecht** [pachterlab/NYMP_2018#5]
Hello and thank you for having a public repo from which to learn how to reproduce your method,

I was trying to look at simulated data. In `NYMP_2018/simulations/RSEM/parameters/info.txt` there is a `hsmm_c1tpms.rds` object mentioned but that is not present in the repo. I believe this is a TPM matrix for the 105 MYOG-expressing proliferating myoblasts (as stated in the methods of your paper) ? 

Could you maybe share that object or the 105 corresponding column names?

Alternatively, could you share the simulated data so that I can simply use it as an input for the various differential expression methods (i.e. an expression matrix derived after the RSEM reads as well as the expression matrix derived from splatter) ?

Thank you for your help
All the best,

**Comment by lynnyi** [comment]
Due to the large sizes of the datasets, I wasn't able to upload the datasets on github, so I used figshare instead. You can find the kallisto quantifications for the RSEM simulations and the counts for splatter simulation here: https://figshare.com/account/projects/38897/articles/7108364

I would prefer to also share the FASTQ files, but those are unfortunately above the Figshare size limit of 20GB.  If you know of an alternative platform to sharing large simulations, let me know.

Best,
Lynn

**Comment by ebecht** [comment]
Hello @lynnyi and thank you,

I am getting a permission error when trying to access the figshare project. Maybe it hasn't been made public yet ?

Best,

**Comment by lynnyi** [comment]
Hi @ebecht,
Thanks for alerting me to this. The link has been updated on the README and is here:
https://figshare.com/articles/Single_Cell_RNA-Seq_Simulations_for_Ntranos_Yi_et_al_2019/7108364

**Comment by ebecht** [comment]
Thank you! I could download the file archive without any issue.
